### ISSUE TITLE
Yandere Simulator Launcher crashes when MVPS hosts file is used

### ISSUE THREAD

**Issue by iotku** [NoxCaos/yanderesimlauncher#1]
[launcherCrashDump.txt](https://github.com/NoxCaos/yanderesimlauncher/files/368238/launcherCrashDump.txt)

Expected Result: Launcher doesn't crash after downloading
Actual Result: Launcher crashes after downloading

Background information: The MVPS Hosts file (http://winhelp2002.mvps.org/hosts.htm) is a fairly popular method of blocking advertisement domains, malware domains, etc by redirecting them to your own computer.

Steps to reproduce:

1) Use the MVPS hosts file (http://winhelp2002.mvps.org/hosts.htm) or otherwise have "0.0.0.0 simplehitcounter.com" in C:\Windows\System32\drivers\etc\HOSTS

2) Start the launcher and it will download Yandere simulator

3) Once the download is finishes it crashes

Possible solution: Remove integration for simplehitcounter or ignore failure.

[Probably responsible code](https://github.com/NoxCaos/yanderesimlauncher/blob/e502791f40aa8379e06edfecd7e3ad6f74aa8dcb/MainWindow.xaml.cs#L271)

**Comment by NoxCaos** [comment]
Request fail ignored by try-block
Thanks for detecting the issue
